### ISSUE TITLE
I cannot start the plugin.

### ISSUE THREAD

**Issue by MasterWindowS** [azalty/sm-ct-bans#1]
Hello, I am having a problem which is that it does not let me start the plugin, and when I start it I get this in the console.

L 09/05/2021 - 05:11:57: [sm_ctban.smx] Default database database connection failure: [2003]: Can't connect to MySQL server on 'localhost' (10061)
L 09/05/2021 - 05:11:57: [SM] Exception reported: Error while connecting to default database. Exiting.
L 09/05/2021 - 05:11:57: [SM] Blaming: sm_ctban.smx
L 09/05/2021 - 05:11:57: [SM] Call stack trace:L 09/05/2021 - 05:11:57: [SM] [0] SetFailStateL 09/05/2021 - 05:11:57: [SM] [1] Line 1599, D:\Perso\expbox\addons\sourcemod\scripting\sm_ctban.sp::DB_Callback_Connect

**Comment by azalty** [comment]
Your database infos are incorrect. Here are the potential causes:
- You didn't setup any MySQL database. (try SQLite instead!)
- Your host parameter is incorrect. You can try "127.0.0.1" instead of "localhost", I personally had this issue.
- Your user/password combination is incorrect.

Please check the value of the cvar sm_ctban_database_driver. The driver `default` is invalid. Edit it, or create a new one that works for ct-bans

**Comment by azalty** [comment]
I'm closing this since I answered you..?
